### ISSUE TITLE
documentation is incorrect for FATAL_STR

### ISSUE THREAD

**Issue by rnburn** [facebook/fatal#5]
From FATAL_STR macro documentation

   // this is equivalent to
   // `using hi = constant_sequence<char, 'h', 'i'>;`
   FATAL_STR("hi") hi;

But the macro takes the type name as the first argument and is used like FATAL(hi, "hi")

**Comment by juchem** [comment]
Thanks a lot for catching this.

**Comment by juchem** [comment]
closed by ed16ea96db447ba1b164c759e70dafa08e9c5e39
