### ISSUE TITLE
Construct a variant using the value

### ISSUE THREAD

**Issue by douglasantos00** [facebook/fatal#9]
Right now, to construct a variant we need to create an empty one and them use `set` or `emplace`. Why not having a constructor that takes the value directly? We already have it for `operator=`:

```
<typename U>
  U &operator =(U const &value)
```

**Comment by juchem** [comment]
IIRC we didn't reach a good enough API regarding overload resolution.
Sounds reasonable, though. I'll take a stab at it again.
